CREATE TABLE Drivers(
    ID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL ,
    LastName VARCHAR(30),
    FirstName VARCHAR(30),
    Suffix VARCHAR(10),
    BirthDate DATE,
    City VARCHAR(30),
    State VARCHAR(30)
);

CREATE TABLE Tracks(
    ID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL ,
    Name VARCHAR(30),
    City VARCHAR(30),
    State VARCHAR(30),
    RaceType MEDIUMINT UNSIGNED,
    Length VARCHAR(30),
    Capacity INT
);

CREATE TABLE Races(
    ID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL ,
    Name INT,
    TrackID MEDIUMINT UNSIGNED,
    Distance INT
);

CREATE TABLE TrackTypes(
    ID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Name VARCHAR(30),
    Description VARCHAR(256)
);

CREATE TABLE RaceResults(
    ID MEDIUMINT UNSIGNED AUTO_INCREMENT NOT NULL,
    DriverID MEDIUMINT UNSIGNED NOT NULL,
    Place INT,
    primary key(ID, DriverID)
);


CREATE TABLE Schedule(
	ID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Year INT NOT NULL, 
    RaceID MEDIUMINT UNSIGNED ,
	DateOfRace DATE NOT NULL,
    TimeOfRace TIME NOT NULL
);
  
ALTER TABLE `Tracks`
ADD CONSTRAINT `FK_Tracks_TrackTypes`
  FOREIGN KEY (RaceType) REFERENCES `TrackTypes`(ID);
  
ALTER TABLE `Races`
ADD CONSTRAINT `FK_Races_Tracks`
    FOREIGN KEY (TrackID) REFERENCES `Tracks`(ID);
    
ALTER TABLE `RaceResults`
ADD CONSTRAINT `FK_RaceResults_Drivers` 
  FOREIGN KEY (DriverID) REFERENCES `Drivers` (ID),
ADD CONSTRAINT `FK_RaceResults_Schedule` 
  FOREIGN KEY (ID) REFERENCES `Schedule`(ID);
    
ALTER TABLE `Schedule`
ADD CONSTRAINT `FK_Schedule_Races`
	FOREIGN KEY (RaceID) REFERENCES `Races`(ID);
